version: '3.4'

services:

  identity.presentation:
    container_name: "Identity.Presentation"
    image: ${DOCKER_REGISTRY-}identitypresentation
    build:
      context: .
      dockerfile: Services/Identity/Identity.Presentation/Dockerfile
    ports:
        - "7000:7000"
        - "7001:7001"

  identity.db:
    container_name: "Identity.Database"
    image: mcr.microsoft.com/mssql/server:2022-latest
    user: root
    volumes:
      - ./.containers/data/identity:/var/lib/mssql/identity
    environment:
        ACCEPT_EULA: "Y"
        MSSQL_SA_PASSWORD: StrongPassword123
    ports:
        - "1433:1433"

  ordering.presentation:
    container_name: "Ordering.Presentation"
    image: ${DOCKER_REGISTRY-}orderingpresentation
    build:
      context: .
      dockerfile: Services/Ordering/Ordering.Presentation/Dockerfile
    ports:
        - "6000:6000"
        - "6001:6001"

  ordering.db:
    container_name: "Ordering.Database"
    image: "mcr.microsoft.com/mssql/server:2022-latest"
    user: root
    volumes:
      - ./.containers/data/ordering:/var/lib/mssql/ordering
    environment:
        ACCEPT_EULA: "Y"
        MSSQL_SA_PASSWORD: StrongPassword123
    ports:
        - "5533:1433"